### ISSUE TITLE
Need to Restart Eclipse on error

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#26] opened 2017-08-10 19:43 UTC
Imported xml file export_2. 
mdmi file created
error in eclipse when opening the file with "mdmi editor"

when this happens, need to restart eclipse to continue work. 
[export_2 - Copy.docx](https://github.com/MDMI/mdmiecore/files/1216133/export_2.-.Copy.docx)

**Comment by swmuir** [comment] 2017-08-18 13:31
Duplicate of 24

**Comment by swmuir** [comment] 2017-10-04 19:13
Duplicate

**Closed by swmuir** 2017-10-04 19:13 UTC
Labels: duplicate
